version: "3.8"
services:
  node:
    container_name: degenbot
    build: .
    volumes:
      - .:/app

    restart: always
    depends_on:
      - db
  db:
    container_name: discorddb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - ./mongodata:/data/db
