version: "3"
services:
  node:
    container_name: degenbot
    build: ./client
    volumes:
      - ./client:/app

    restart: always
    depends_on:
      - db
  db:
    container_name: discorddb
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - ./mongodata:/data/db
    command: mongod --quiet --logpath /dev/null
  dashboard:
    container_name: botdashboard
    build: ./frontend/bot-dashboard
    ports:
      - 3000:3000
    depends_on:
      - db
  dashboardapi:
    container_name: dashboardapi
    build: ./frontend/dashboard-api
    ports:
      - 5000:5000
    volumes:
      - ./frontend/dashboard-api:/app
    depends_on:
      - db
